# Generated by Django 6.0 on 2026-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventregistration_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
