# Generated by Django 6.0 on 2026-01-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='banner',
            new_name='image',
        ),
    ]
