# Generated by Django 6.0 on 2026-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_banner_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
