# Generated by Django 6.0 on 2026-01-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_benefits_event_importance_event_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='event',
            name='importance',
        ),
    ]
